apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: node
  type: LoadBalancer