vpc_cidr_block =  "10.10.0.0/16"
region         = "us-east-1"
subnet_cidr_block = "10.10.0.0/24"
avail_zone = "us-east-1a"
env_prefix = "Test"
instance_type = "t2.large"
bucket_name = "domo-bucket-project1"
